const DATA = {
  cleansers: {
    id: 1,
    title: 'Cleansers',
    routeName: 'cleansers',
    items: [
      {
        id: 101,
        name: 'Pore Clearing Cleansing Oil',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/MnJ7QV1/pccoil-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'cleanser',
        sizes: ['1oz', '4oz', '8oz'],
        featured: true,
      },
      {
        id: 102,
        name: 'Pore Purifying Cleanser',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/Z2WVxpL/ppc-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'cleanser',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 103,
        name: 'Restorative Creamy Cleanser',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/tDvVWJD/rcc-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'cleanser',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 104,
        name: 'Hydrating Face Wash',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/z5vTn96/hfw-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'cleanser',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 105,
        name: 'Gentle Cleansing Mils',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/89TQ7hT/gcm-retail.jpg',
        price: 18,
        company: 'Michele Corley Clinical Skincare',
        category: 'cleanser',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 106,
        name: 'Corrective Salicylic Cleanser',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/Z1hj6hY/csc-retail-1.jpg',
        price: 18,
        company: 'Michele Corley Clinical Skincare',
        category: 'cleanser',
        sizes: ['1oz', '4oz', '8oz'],
      },

    ]
  },
  specialty: {
    id: 2,
    title: 'Specialty',
    routeName: 'specialty',
    items: [
      {
        id: 101,
        name: 'Glycolic Cream',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/HBfL6wR/glycolic-cream.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'specialty',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 202,
        name: 'Purifying Oxygen Lotion',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/4RzBbLr/pur-Oxy-retail-3.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'specialty',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 203,
        name: 'Vitamin C Powder',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/wy1R7hV/vitpwd-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'specialty',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 204,
        name: 'Balance Essential Oil Blend',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/BfXxP8c/balance.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'specialty',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 205,
        name: 'Plump Me Up Hydrating Mist',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/zHw7Cbg/hmist-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'toner',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 206,
        name: 'Pore Purifying Toner',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/m42BpKx/ppt-retail.jpg',
        price: 20,
        company: 'Michele Corley Clinical Skincare',
        category: 'toner',
        sizes: ['1oz', '4oz', '8oz'],
      },
    ]
  },
  serums: {
    id: 3,
    title: 'Serums',
    routeName: 'serums',
    items: [
      {
        id: 301,
        name: 'Blemish Be Gone',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/HPPb2Wk/bbg-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 302,
        name: 'Brighten & Restore Complex',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/6Wnn5SK/bandr.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 303,
        name: 'Calm, Nourish & Repair Oil',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/4dLfnCX/cnr-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 304,
        name: 'Calming Serum',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/23MyR0w/calming-serum.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 305,
        name: 'Glycolic Age Defying Serum',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/74c3wb2/glycolic-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 306,
        name: 'Hyaluronic Plumping Serum',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/KKRSKPC/hyal-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
        featured: true,
      },
      {
        id: 307,
        name: 'Licorice Root Additive',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/jvFYNcP/licorice.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
        featured: true,
      },
      {
        id: 308,
        name: 'Lipid Replenishing Drops',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/Jr1nFwN/lipid-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 309,
        name: 'Prime & Protect Serum',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/3msMNHN/pprotect-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 310,
        name: 'Rejuvenating Peptide & Stem Cell Serum',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/LRQnDys/rejpepserum-retail.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 311,
        name: 'Vitamin C Serum Plus',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/QXDyN53/vit-c.jpg',
        price: 35,
        company: 'Michele Corley Clinical Skincare',
        category: 'serum',
        sizes: ['1oz', '4oz', '8oz'],
      },
    ]
  },
  eyeslips: {
    id: 4,
    title: 'Eyes & Lips',
    routeName: 'eyeslips',
    items: [
      {
        id: 401,
        name: 'Peptide Rich & Radiant Eye Cream',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/Lvhxj9M/rareye-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'eye',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 402,
        name: 'Plump & Renew Lip Balm',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/0JJcQjz/prlip-retail.jpg',
        price: 20,
        company: 'Michele Corley Clinical Skincare',
        category: 'lip',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 403,
        name: 'Revitalizing Peptide & Stem Cell Eye Gel',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/4KdScL9/reveyegel-dpr-pump.jpg',
        price: 20,
        company: 'Michele Corley Clinical Skincare',
        category: 'eye',
        sizes: ['1oz', '4oz', '8oz'],
      },
    ]
  },
  moisturizers: {
    id: 5,
    title: 'Moisturizers',
    routeName: 'moisturizers',
    items: [
      {
        id: 501,
        name: 'Clarifying Moisturizer',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/QHfb3D9/clarifying-moisturizer.jpg',
        price: 20,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 502,
        name: 'Hydrating Moisture Cream',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/qnNpJ1w/hydrating-moisture-cream.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 503,
        name: 'Oil-Free Moisturizer',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/cN0dhJy/oil-free.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 504,
        name: 'Calming Moisture Cream',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/HCjMvPz/calming-moisture-cream-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 505,
        name: 'Ultra Rich Moisture Cream',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/cL07G8V/ultra-Rich-retail.jpg',
        price: 325,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 506,
        name: 'Ultimate Hydration Gel',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/TY4Wnnk/ulthyd.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 507,
        name: 'Moisturizing SPF 30',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/8bs6Y8J/spf30.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 508,
        name: 'Purifying Oxygen Lotion',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/4RzBbLr/pur-Oxy-retail-3.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['1oz', '4oz', '8oz'],
      },
      {
        id: 509,
        name: 'Vitamin A & E Hand & Body Lotion',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/SB19xMP/handbody-retail.jpg',
        price: 25,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['4oz'],
      },
      {
        id: 510,
        name: 'Moisturizing SPF 30 Complexion Corrector',
        desc: 'This refreshing, purifying gel cleanser helps balance acne-prone, oily and congested skin. The natural exfoliating properties of Willow Bark Extract unclog pores while pore purifying essential oils, Eucalyptus and Sage, stop problems before they start.',
        imageUrl: 'https://i.ibb.co/NF9ssw6/spf30-tints.jpg',
        price: 40,
        company: 'Michele Corley Clinical Skincare',
        category: 'moisturizer',
        sizes: ['4oz'],
      },
    ]
  }
};

const allData = [];
DATA.cleansers.items.forEach(item => allData.push(item))
DATA.specialty.items.forEach(item => allData.push(item))
DATA.serums.items.forEach(item => allData.push(item))
DATA.eyeslips.items.forEach(item => allData.push(item))
DATA.moisturizers.items.forEach(item => allData.push(item))

export {DATA, allData}
